# Generated by Django 5.1.1 on 2024-10-09 19:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha pub')),
                ('resumen', models.TextField(max_length=200, verbose_name='resumen')),
                ('texto', models.TextField(verbose_name='Contenido')),
                ('activo', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, upload_to='media')),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(default='Sin categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.categoria')),
            ],
        ),
    ]
